version: "3.8"
services:
  frontend:
    build: .
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - tmsnet

  backend:
    build: .
    command: node ./src/server/express-server.js
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://root:password@db:3306/taskmanager
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-token-key
      - SESSION_SECRET=your-session-secret-key
    depends_on:
      - db
      - redis
    networks:
      - tmsnet

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: taskmanager
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - tmsnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - tmsnet

volumes:
  db_data:

networks:
  tmsnet:
    driver: bridge
