// Tasks API constants
export const TASKS_UPDATE_SEARCH_CONDITIONS = "TASKS_UPDATE_SEARCH_CONDITIONS";
export const TASKS_UPDATE_SEARCH_QUERY_STRING =
  "TASKS_UPDATE_SEARCH_QUERY_STRING";

// Auth constants
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_RESET_ERROR = "AUTH_RESET_ERROR";
export const AUTH_CHANGE_PASSWORD = "AUTH_CHANGE_PASSWORD";

// App constants
export const APP_START_LOADING = "APP_START_LOADING";
export const APP_END_LOADING = "APP_END_LOADING";
export const APP_ADD_NOTIFICATION = "APP_ADD_NOTIFICATION";
export const APP_REMOVE_NOTIFICATION = "APP_REMOVE_NOTIFICATION";
export const APP_CLEAR_NOTIFICATION = "APP_CLEAR_NOTIFICATION";
